PROJECT: "listops_expectation"
DATASET:
  NAME: ListOps
  MIN_LEN: 500
  MAX_LEN: 2000
  MAX_DEPTH: 10
  MAX_ARGS: 10
  TEST_SIZE: 2000
  TRAIN_SIZE: 96000
  VAL_SIZE: 2000
  GENERATE: False
  PREPROCESSED: True
MODEL:
  ACTIVATION: $torch.nn.GELU 
  BIAS: True
  INPUT_SIZE: 128
  N_LAYERS: 6
  KERNEL_VERSION: gamma
  BIDIRECTIONAL: False
  ENCODING: embedding
  POOLING: average
  NAME: DSS
  DROPOUT: 0.
  NORMALIZATION: batch_norm
  SEED: [712,8,93] #[712,8,93,74,812]
TRAIN:
  BATCH_SIZE: 50
  DISPLAY_EPOCH: True
  DISPLAY_EVERY: null
  LOSS_FN: $torch.nn.CrossEntropyLoss
  LOSS_CONFIG: null
  METRICS: {'accuracy': $torchmetrics.Accuracy}
  METRICS_CONFIG:
    task: multiclass
    num_classes: 10
  N_EPOCHS: 50
  OPTIMIZER: $torch.optim.AdamW
  OPTIMIZER_CONFIG:
    lr: [5.e-3,1.e-4]
    weight_decay: 1.e-2
  SCHEDULER: $torch.optim.lr_scheduler.ReduceLROnPlateau
  SCHEDULER_CONFIG:
    patience: 5
  TORCH_DEVICE: cpu
  USE_TQDM: False
  USE_WANDB: False