PROJECT: "seq_CIFAR10_expectation"
DATASET:
  NAME: sCIFAR10
  TRAIN_SIZE: 45000
  VAL_SIZE: 5000
MODEL:
  ACTIVATION: $torch.nn.GELU 
  BIAS: True
  BIDIRECTIONAL: False
  DROPOUT: 0.2
  ENCODING: linear
  INPUT_SIZE: 512
  KERNEL_VERSION: gamma
  N_LAYERS: 6
  NAME: DSS
  NORMALIZATION: layer_norm
  POOLING: average
  SEED: [712,8,93] #[712,8,93,74,812]
  STATE_SIZE: 64
TRAIN:
  BATCH_SIZE: 50
  DISPLAY_EPOCH: True
  DISPLAY_EVERY: null
  LOSS_FN: $torch.nn.CrossEntropyLoss
  LOSS_CONFIG: null
  METRICS: {'accuracy': $torchmetrics.Accuracy}
  METRICS_CONFIG:
    task: multiclass
    num_classes: 10
  N_EPOCHS: 50
  OPTIMIZER: $torch.optim.AdamW
  OPTIMIZER_CONFIG:
    lr: [5.e-3,1.e-4]
    weight_decay: 1.e-2
  SCHEDULER: $torch.optim.lr_scheduler.ReduceLROnPlateau
  SCHEDULER_CONFIG:
    patience: 10
  TORCH_DEVICE: cpu
  USE_TQDM: False
  USE_WANDB: False