PROJECT: "copytask_DSS"
DATASET:
  NAME: CopyMemory
  SENT_LENGTH: 10
  SEQ_LENGTH: 1000
  TEST_SIZE: 2000
  TRAIN_SIZE: 51200
  VAL_SIZE: 2000
  VOCABULARY: 10
MODEL:
  INPUT_SIZE: 128
  STATE_SIZE: 64
  ACTIVATION: $torch.nn.GELU 
  BIAS: True
  BIDIRECTIONAL: False
  NAME: DSS
  ENCODING: embedding
  POOLING: manytomany
  NORMALIZATION: batch_norm
  DROPOUT: 0.
  N_LAYERS: 6
  SEED: [712,8]
TRAIN:
  BATCH_SIZE: 32
  DISPLAY_EPOCH: True
  DISPLAY_EVERY: null
  LOSS_FN: $torch.nn.CrossEntropyLoss
  LOSS_CONFIG: null
  METRICS: null
  N_EPOCHS: 6
  OPTIMIZER: $torch.optim.AdamW
  OPTIMIZER_CONFIG:
    lr: 1.e-3
  SCHEDULER: $torch.optim.lr_scheduler.StepLR
  SCHEDULER_CONFIG:
    gamma: 1.
    step_size: 1
  TORCH_DEVICE: cpu
  USE_TQDM: True
  USE_WANDB: False