PROJECT: "copytask_DSS"
DATASET:
  NAME: CopyMemory
  SENT_LENGTH: 10
  SEQ_LENGTH: 1000
  TEST_SIZE: 2000
  TRAIN_SIZE: 512000
  VAL_SIZE: 2000
  VOCABULARY: 10
MODEL:
  ACTIVATION: $torch.nn.GELU
  BIAS: True
  BIDIRECTIONAL: False
  DROPOUT: 0.
  ENCODING: embedding
  INPUT_SIZE: 128
  KERNEL_VERSION: exp
  N_LAYERS: 6
  NAME: DSS
  NORMALIZATION: batch_norm
  POOLING: manytomany
  SEED: [712,8,93] #[712,8,93,74,812]
  STATE_SIZE: 2
TRAIN:
  BATCH_SIZE: 50
  DISPLAY_EPOCH: True
  DISPLAY_EVERY: null
  LOSS_FN: $torch.nn.CrossEntropyLoss
  LOSS_CONFIG: null
  METRICS: null
  N_EPOCHS: 15
  OPTIMIZER: $torch.optim.AdamW
  OPTIMIZER_CONFIG:
    lr: 1.e-3
    weight_decay: 1.e-2
  SCHEDULER: $torch.optim.lr_scheduler.ReduceLROnPlateau
  SCHEDULER_CONFIG:
    patience: 5
  TORCH_DEVICE: cpu
  USE_TQDM: False
  USE_WANDB: False